name: quizzype001
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.2
  animated_text_kit: ^4.2.1
  pie_chart: ^5.4.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.4.0
  country_code_picker: ^3.0.0
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  permission_handler: ^11.2.0
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  readmore: ^2.2.0
  device_info_plus: ^9.1.1
  flashy_tab_bar2: ^0.0.6
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^16.2.0
  flutter_phoenix: ^1.1.1
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  vibration: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  share_plus: ^10.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "Assets/Images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^2.3.2
  flutter_lints: ^3.0.0
flutter:


  uses-material-design: true

  assets:
    - Assets/Images/
    - Assets/Images/Animation.json

